### ISSUE TITLE
Toggle Password Settings

### ISSUE THREAD

**Issue by anders-akero** [kartik-v/yii2-password#12]
How do I remove the toggle password checkbox?

In the documentation it says:
echo $form->field($model, 'password')->widget(PasswordInput::classname(), [
    'showMeter' => true,
    'toggleMask' => false
]);
But that gives me this error: Setting unknown property: kartik\password\PasswordInput::showMeter

**Comment by egozo** [comment]
I cant remove even now.
No error but in view there is a bug.
![121212](https://cloud.githubusercontent.com/assets/10882920/8669688/46381ae6-2a1f-11e5-831c-cb62ec716f84.PNG)

**Comment by kartik-v** [comment]
You may update to latest and try.

Check the [second example in demo](http://demos.krajee.com/password-details/password-input#advanced-usage).

**Comment by egozo** [comment]
thanks, but option 'toggleMask' => false dont work for me...
I have the version 1.5.0 release.

**Comment by kartik-v** [comment]
You have an older release.

As I said the latest release... the latest now is [release 1.5.2](https://github.com/kartik-v/yii2-password/releases/tag/v1.5.2).

**Comment by kartik-v** [comment]
As I mentioned you must update to the latest release... you have the older release. The latest release now is release 1.5.2.

**Comment by egozo** [comment]
I updated to 1.5.2 but it didn`t suit
still need your help

**Comment by kartik-v** [comment]
You must update via composer... it will update dependent packages.

If you have manually copied files it will not work.

**Comment by egozo** [comment]
it`s ok
thanks
very good work

**Comment by egozo** [comment]
Maybe you know why after updated all components there is a new border in nav widget (bootstrap)?




>Вторник, 14 июля 2015, 6:57 -07:00 от Kartik Visweswaran <notifications@github.com>:
>
>You must update via composer... it will update dependent packages.
>If you have manually copied files it will not work.
>—
>Reply to this email directly or  view it on GitHub .


С уважением,
Тимофей П.
tp@inbox.ru
