### ISSUE TITLE
Spelling in polish translation

### ISSUE THREAD

**Issue by itzen** [kartik-v/yii2-password#19]
There is an error in Polsih translation:
{atrribute} should be {attribute} (line 28 in pl/kvpwdstrength.php)

'{attribute} should contain at least {n, plural, one{one numeric / digit character} other{# numeric / digit characters}} ({found} found)!' => '{atrribute} powinno zawierać przynajmniej {n, plural, =1{jedną cyfrę} few{# cyfry} other{# cyfr}}  ({found} znaleziono)!',

**Comment by kartik-v** [comment]
Fixed via #20.
