### ISSUE TITLE
Overriding translation messages in config does not work

### ISSUE THREAD

**Issue by cronfy** [kartik-v/yii2-password#40]
I am trying to override messages file via yii2 config, but it does not work:

```php
    'components' => [
        'i18n' => [
            'translations' => [
                'kvpwdstrength*' => [ //
                    'class' => 'yii\i18n\PhpMessageSource',
                    'basePath' => '@app/messages', // my custom message path.
                    'sourceLanguage' => 'en-US',
                    'fileMap' => [
                        'kvpwdstrength' => 'kvpwdstrength.php', 
                    ],
                ]
            ],
        ],
    ],
```

This config could work, but it does not, because config is overriden in `kartik\base\TranslationTrait`.

Is there another way to override messages or it is a bug? Please give a hint.

**Comment by kartik-v** [comment]
You need to set i18n property of the `StrengthValidator` directly.

Check [the docs](http://demos.krajee.com/password-details/strength-validator) for supported strength validator settings

**Comment by cronfy** [comment]
I use dektrium/yii2-user for user management. There are at least two places where I need to use StrengthValidator: Registration form and user Settings form.

It is not very convenient to repeat same i18n confguration in every place where StrengthValidator is used, global setting would be preferable. Also i18n config does not seem to be on it's best place when set among validation rules.

Why not make TranslationTrait::initI18N() to take care of global translation settings from yii2 config? Something like this:

```php
    public function initI18N($dir = '', $cat = '')
    {

... ... ...

        } else {
            $i18n = $this->i18n;
        }

        $current_config = isset(Yii::$app->i18n->translations["{$cat}*"])
            ? Yii::$app->i18n->translations["{$cat}*"]
            : [];

        Yii::$app->i18n->translations["{$cat}*"] = array_merge($i18n, $current_config);
    }
```

It makes possible to set global translation settings for yii2-password with config I posted in previous comment. Base i18n settings used as defaults and settings from yii2 config override them.

I can create a pull request for this.

**Comment by kartik-v** [comment]
Sure you can submit a PR... opening this.
