### ISSUE TITLE
Can not use StrengthValidator if I only have one form field ( password )

### ISSUE THREAD

**Issue by nenad-zivkovic** [kartik-v/yii2-password#41]
If I have reset password form with only one field in it ( password ), I can not use normal+ presets, because for some reason it is mandatory to have username (and email) fields/attributes and validate against them too ?

It seems like these widgets are not flexible enough to not bother you with other fields and their rules if you do not need/have them.

So if you have just password to validate, sintax like this should be enough:

`[['password'], StrengthValidator::className(), 'preset'=>'normal']`

or if your field is not named password, you should be able to do this:

`[['password'], StrengthValidator::className(), 'preset'=>'normal', 'passwordField' => 'pwd']`

If you have username and password, this should be enough:

`[['password'], StrengthValidator::className(), 'preset'=>'normal', 'usernameField' => 'username', 'passwordField' => 'pwd']`

Also, in last example, it would be nice if you can decide whether or not you should validate password by checking if username is in it.

and so on...

Is this possible now somehow but I am missing something ?

**Comment by kartik-v** [comment]
Just use the validator without a preset for your unique customized scenario. 

For example set `hasUser` to `false` and `hasEmail` to `false`. Check [the docs](http://demos.krajee.com/password-details/strength-validator) for supported strength validator settings
