### ISSUE TITLE
Error in the Russian text

### ISSUE THREAD

**Issue by den1008** [kartik-v/yii2-password#59]
In file messages/ru/kvpwdstrength string 35:
`'{attribute} должен содержать минимум {n, plural, one{# цифру} few{# цыфры} many{# цифер} many{# цифр} other{# цифр}} ({found} найдено)!',` twice indicated many. 
many{# цифер} - is an error.
Need `'{attribute} должен содержать минимум {n, plural, one{# цифру} few{# цыфры} many{# цифр} other{# цифр}} ({found} найдено)!',`

**Comment by kosov** [comment]
"цыфры" should be replaced by "цифры".

**Comment by kartik-v** [comment]
Thanks - can you please submit a PR?

**Comment by den1008** [comment]
ok

**Comment by kartik-v** [comment]
Thanks merged #61.
