### ISSUE TITLE
kartik\password\StrengthValidator and kartik\base\TranslationTrait define the same property ($_msgCat) in the composition of kartik\password\StrengthValidator.

### ISSUE THREAD

**Issue by mhoogstraten** [kartik-v/yii2-password#63]
## Prerequisites
Use StrengthValidator and php 7.2>

## Steps to reproduce the issue
new StrengthValidator();

Shows the following error:
yii\base\ErrorException: kartik\password\StrengthValidator and kartik\base\TranslationTrait define the same property ($_msgCat) in the composition of kartik\password\StrengthValidator. However, the definition differs and is considered incompatible. Class was composed in **\vendor\kartik-v\yii2-password\StrengthValidator.php:26

## Environment
Yii2 2.0.15.1
PHP 7.2.9
kartik-v/yii2-password: 1.5.3

**Comment by kartik-v** [comment]
Yes you are using an older version of yii2-password - latest version is 1.5.4. 

Update packages using composer to get latest package with all the updated dependencies to other extensions.
